version: '3.9'

services:
  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    hostname: mongodb
    volumes:
      - mongodb-data:/data/db/
      - mongodb-log:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - mongodb_network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - 8081:8081
    networks:
      - mongodb_network
    depends_on:
      - mongodb
  
  imp-api:
    build: .
    container_name: imp-api
    restart: always
    environment:
      MONGODB_URL: 'mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb/'
      OBJ_STORAGE_ACCESS_KEY: ${OBJS_ACCESS_KEY}
      OBJ_STORAGE_SECRET_KEY: ${OBJS_SECRET_KEY}
      OBJ_STORAGE_ENDPOINT_URL: http://minio:9000
      OBJ_STORAGE_BUCKET: imp-images
    ports:
      - 17001:17001
    networks:
      - mongodb_network
      - minio_network
    depends_on:
      - mongodb
      - minio

  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: ${OBJS_ACCESS_KEY}
      MINIO_SECRET_KEY: ${OBJS_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - minio_network

volumes:
  mongodb-data:
    driver: local
    name: mongo-data
  mongodb-log:
    driver: local
    name: mongo-log
  minio-data:
    driver: local
    name: minio-data

networks:
  mongodb_network:
    driver: bridge
    name: mongo-network
  minio_network:
    driver: bridge
    name: minio-network